# Generated by Django 4.0.4 on 2022-06-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial1', models.CharField(default='', max_length=200)),
                ('initial2', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('family_area', models.FloatField()),
                ('family_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.familytype')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.offer')),
                ('progress_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.progressstate')),
            ],
        ),
    ]
