# Generated by Django 4.0.4 on 2022-06-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_familytype_f_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transalations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=200)),
                ('family_type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='familytype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='familytype',
            name='f_name',
        ),
        migrations.AddField(
            model_name='familytype',
            name='f_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.transalations'),
        ),
    ]
