# Generated by Django 4.0.4 on 2022-06-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_transalations_remove_familytype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familytype',
            name='f_specifications',
        ),
        migrations.AddField(
            model_name='familytype',
            name='f_specifications',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.transalations'),
        ),
    ]
