# Generated by Django 4.0.4 on 2022-06-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_familytype_f_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytype',
            name='f_specifications',
            field=models.ManyToManyField(to='myApp.transalations'),
        ),
    ]
