# Generated by Django 4.0.4 on 2022-06-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_familytype_f_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStatesTransalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='transalations',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressstate',
            name='languages',
            field=models.ManyToManyField(to='myApp.progressstatestransalation'),
        ),
    ]
